version: "3.3"
services:
  
  myserver:
    image: twitter_server:latest
    # image: kevineqcontainer.azurecr.io/twitter_server:latest
    # container_name: kevineqserver
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 4G

    build:
      context: ./
      dockerfile: server/Dockerfile

    ports: 
      - 9095

    env_file:
      - ./.env
    
    networks:
      - mynetwork

  myclient:
    image: twitter_client:latest
    # image: kevineqcontainer.azurecr.io/twitter_client:latest
    # container_name: kevineqclient
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 4G

    build: 
      context: ./
      dockerfile: client/Dockerfile
    
    env_file:
      - ./.env

    networks:
      - mynetwork

    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    depends_on:
      - myserver

networks:
  mynetwork:
    driver: bridge